<a href="https://colab.research.google.com/github/gbiamgaurav/PyTorch-Tutorials/blob/main/01_Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


### Creating a Tensor

In [ ]:
# Using empty

a = torch.empty(2, 3)

In [ ]:
# Check type

type(a)

torch.Tensor

In [ ]:
# Using zeros

torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using ones

torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using rand

torch.rand(2, 3)

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])

In [ ]:
# Use of seed

torch.rand(2, 3)

tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]])

In [ ]:
# Manual seed

torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# Using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
## Other ways

# arange

print(f"Using arange -> ", torch.arange(0, 10))

# linspace

print(f"Using linspace -> ", torch.linspace(0, 10, 10))

# eye

print(f"Using eye -> ", torch.eye(5))

# full

print(f"Using full -> ", torch.full((3, 3), 5))

Using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067809043692399925, 4050207427138302769, 6499594969319224366]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

### Tensor Data Type

In [ ]:
# find data type

x.dtype

torch.int64

In [ ]:
# assign data type

torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

### 1. Scalar Operation

In [ ]:
x = torch.rand(2, 2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [ ]:
# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x * 3)

# division
print(x / 3)

# int division
print((x * 100)//3)

# mod
print(((x * 100))%2)

# power
print(x ** 2)

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])
tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])
tensor([[2.6082, 1.7031],
        [2.2233, 1.2882]])
tensor([[0.2898, 0.1892],
        [0.2470, 0.1431]])
tensor([[28., 18.],
        [24., 14.]])
tensor([[0.9404, 0.7715],
        [0.1094, 0.9404]])
tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])


### 2. Element wise operation

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [ ]:
# addition
print(a+b)

# substraction
print(a-b)

# multiplication
print(a*b)

# division
print(a/b)

# floor division
print(a//b)

# mod
print(a%b)

# power
print(a**b)

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])
tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])
tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])
tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])
tensor([[2., 0., 2.],
        [2., 0., 2.]])
tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])
tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])


In [ ]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#### Reduction operation

In [ ]:
e = torch.randint(size=(2, 3), low=2, high=10, dtype=torch.float32)
e

tensor([[9., 5., 6.],
        [2., 5., 3.]])

In [ ]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along rows
print(torch.sum(e, dim=1))

tensor(30.)
tensor([11., 10.,  9.])
tensor([20., 10.])


In [ ]:
# mean
print(torch.mean(e))

# mean along columns
print(torch.mean(e, dim=0))

# mean along rows
print(torch.mean(e, dim=1))

tensor(5.)
tensor([5.5000, 5.0000, 4.5000])
tensor([6.6667, 3.3333])


In [ ]:
# median
print(torch.median(e))

tensor(5.)


In [ ]:
# max and min
torch.max(e)

torch.min(e)

tensor(2.)

In [ ]:
# product
torch.prod(e)

tensor(8100.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.4495)

In [ ]:
# variance
torch.var(e)

tensor(6.)

In [ ]:
e

tensor([[9., 5., 6.],
        [2., 5., 3.]])

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

In [ ]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2, 3), low=1, high=10)
g = torch.randint(size=(3, 2), low=1, high=10)

print(f)

print(g)

tensor([[6, 5, 1],
        [3, 4, 1]])
tensor([[2, 1],
        [8, 5],
        [2, 6]])


In [ ]:
# matrix multiplication

torch.matmul(f, g)

tensor([[54, 37],
        [40, 29]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose

f

tensor([[6, 5, 1],
        [3, 4, 1]])

In [ ]:
torch.transpose(f, 0, 1)

tensor([[6, 3],
        [5, 4],
        [1, 1]])

In [ ]:
h = torch.randint(size=(3,3), low=1, high=10, dtype=torch.float32)
h

tensor([[3., 4., 7.],
        [8., 3., 8.],
        [8., 6., 9.]])

In [ ]:
# determinant
torch.det(h)

tensor(73.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2877,  0.0822,  0.1507],
        [-0.1096, -0.3973,  0.4384],
        [ 0.3288,  0.1918, -0.3151]])

#### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)

print(j)

tensor([[0, 3, 7],
        [5, 7, 1]])
tensor([[5, 7, 5],
        [8, 5, 4]])


In [ ]:
# greater than
i > j

tensor([[False, False,  True],
        [False,  True, False]])

In [ ]:
# less than
i < j

tensor([[ True,  True, False],
        [ True, False,  True]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than equal to
i >= j

tensor([[False, False,  True],
        [False,  True, False]])

In [ ]:
# less than equal to
i <= j

tensor([[ True,  True, False],
        [ True, False,  True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[1, 1, 0],
        [9, 0, 9]])

In [ ]:
# log
torch.log(k)

tensor([[0.0000, 0.0000,   -inf],
        [2.1972,   -inf, 2.1972]])

In [ ]:
# exponent
torch.exp(k)

tensor([[2.7183e+00, 2.7183e+00, 1.0000e+00],
        [8.1031e+03, 1.0000e+00, 8.1031e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1., 1., 0.],
        [3., 0., 3.]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.7311, 0.5000],
        [0.9999, 0.5000, 0.9999]])

In [ ]:
l = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
l

tensor([[1., 8., 9.],
        [6., 7., 6.]])

In [ ]:
# softmax
torch.softmax(l, dim=0)

tensor([[0.0067, 0.7311, 0.9526],
        [0.9933, 0.2689, 0.0474]])

In [ ]:
torch.softmax(l, dim=1)

tensor([[2.4518e-04, 2.6888e-01, 7.3088e-01],
        [2.1194e-01, 5.7612e-01, 2.1194e-01]])

In [ ]:
# relu
torch.relu(l)

tensor([[1., 8., 9.],
        [6., 7., 6.]])

### Inplace operations

In [ ]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.1568, 0.2083, 0.3289],
        [0.1054, 0.9192, 0.4008]])
tensor([[0.9302, 0.6558, 0.0766],
        [0.8460, 0.3624, 0.3083]])


In [ ]:
m + n

tensor([[1.0870, 0.8641, 0.4055],
        [0.9514, 1.2817, 0.7091]])

In [ ]:
m.add_(n) # inplace operation using _

tensor([[2.0172, 1.5199, 0.4821],
        [1.7974, 1.6441, 1.0174]])

In [ ]:
torch.relu(m)

tensor([[1.0870, 0.8641, 0.4055],
        [0.9514, 1.2817, 0.7091]])

In [ ]:
m.relu_()

tensor([[2.0172, 1.5199, 0.4821],
        [1.7974, 1.6441, 1.0174]])

### Copying a tensor

In [ ]:
a = torch.rand(2, 3)
a

tensor([[0.0850, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
b = a
b

tensor([[0.0850, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
a[0][0] = 0
a

tensor([[0.0000, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
b

tensor([[0.0000, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
b = a.clone()
b

tensor([[0.0000, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
a

tensor([[0.0000, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[1.0000e+01, 2.9197e-03, 6.4306e-01],
        [3.9078e-01, 6.9466e-01, 8.9668e-02]])

In [ ]:
b

tensor([[0.0000, 0.0029, 0.6431],
        [0.3908, 0.6947, 0.0897]])

### Reshaping Tensors

In [200]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [201]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [202]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [203]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.8712, 0.1330, 0.4137, 0.6044],
         [0.7581, 0.9037, 0.9555, 0.1035],
         [0.6258, 0.2849, 0.4452, 0.1258]],

        [[0.9554, 0.1330, 0.7672, 0.6757],
         [0.6625, 0.2297, 0.9545, 0.6099],
         [0.5643, 0.0594, 0.7099, 0.4250]]])

In [204]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [205]:
# unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [206]:
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 3])

In [207]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(dim=0).shape

torch.Size([20])

### Numpy and PyTorch

In [208]:
import numpy as np

In [209]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [210]:
b = a.numpy()
b

array([1, 2, 3])

In [211]:
type(b)

numpy.ndarray

In [212]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [213]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])

In [214]:
type(d)

torch.Tensor