<a href="https://colab.research.google.com/github/gbiamgaurav/PyTorch-Tutorials/blob/main/02_Autograd_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
def dy_dx(x):
  return 2 * x

In [35]:
dy_dx(3)

6

In [36]:
import torch

In [37]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [38]:
y = x ** 2

In [39]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [40]:
y.backward()

In [41]:
x.grad

tensor(6.)

In [42]:
import math

def dz_dx(x):
  return 2 * x * math.cos(x**2)

In [43]:
dz_dx(3)

-5.466781571308061

In [44]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [45]:
y = x ** 2

In [46]:
z = torch.sin(y)

In [47]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [48]:
z.backward()

In [49]:
x.grad

tensor(-5.4668)

In [50]:
import torch

# inputs
x = torch.tensor(6.7)  # Input Feature
y = torch.tensor(0.0)  # True Label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [51]:
# Binary cross-entropy loss for scalar
def binary_cross_entropy(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
  return - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [52]:
# Forward pass

z = w * x + b  # Weighted sum
y_pred = torch.sigmoid(z)

# Compute binary cross entropy loss
loss = binary_cross_entropy(y_pred, y)

In [53]:
loss

tensor(6.7012)

In [54]:
# derivates
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred * (1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivate)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x
dz_db = 1

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [55]:
print(f"Mannual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Mannual Gradient of loss w.r.t bias (db): {dL_db}")

Mannual Gradient of loss w.r.t weight (dw): 6.691762447357178
Mannual Gradient of loss w.r.t bias (db): 0.998770534992218


In [56]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [57]:
we = torch.tensor(1.0, requires_grad=True)
bi = torch.tensor(0.0, requires_grad=True)

In [58]:
z = we * x + bi
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [59]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [60]:
loss = binary_cross_entropy(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [61]:
loss.backward()

In [63]:
print(we.grad)
print(bi.grad)

tensor(6.6918)
tensor(0.9988)


In [64]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [65]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [69]:
y.backward()

In [70]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [71]:
# Clearing grad

x = torch.tensor([2.0], requires_grad=True)
x

tensor([2.], requires_grad=True)

In [72]:
y = x ** 2
y

tensor([4.], grad_fn=<PowBackward0>)

In [73]:
y.backward()

In [74]:
x.grad

tensor([4.])

In [75]:
x.grad.zero_()

tensor([0.])